name = "new smp modpack"
author = "Gurkan"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7a63ba3639bc42e7cca172d4e5452f0cf3e2acc864534b57080bb56f17d618db"

[versions]
fabric = "0.16.13"
minecraft = "1.21.1"
